Repository ExpressLRS/Docs, pull requests merged in 2021-08, with the labels that each got.

#19 Namimno Docs
  docs/assets/images/STM32-updater.png
  docs/assets/images/WifiManager.png
  docs/assets/images/WifiUpdateLog.png
  docs/quick-start/rx-fcprep.md
  docs/quick-start/rx-flash2400.md
  docs/quick-start/rx-jumper900.md
  docs/quick-start/rx-voyager900.md
  docs/quick-start/tx-flash2400.md
  docs/quick-start/tx-voyager900.md
Labels: enhancement

#15 new lua guide
  docs/assets/images/lua3.jpg
  docs/assets/images/lua4.jpg
  docs/quick-start/tx-prep.md
Labels: do not merge, v1.1

#23 Dark Mode
  docs/assets/stylesheets/colors.css
  docs/assets/stylesheets/main.css
  mkdocs.yml
Labels: enhancement

#31 [1.1] Add dynamic transmit power
  docs/quick-start/tx-prep.md
  docs/software/dynamic-transmit-power.md
Labels: enhancement, v1.1
